name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 # build-ubuntu:
  #  runs-on: ubuntu-latest
    

  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
        
      # Generate sln
      - name: generate-sln
        run: cmake -B build
   
      # Build engine Release
      - name: build-sln-Release
        shell: cmd
        run: |
          @echo | msbuild -m build/cpputils.vxproj /t:build /p:Configuration="Release" /p:Platform="x64" /p:BuildInParallel=true
          
      # Prepare package Release
      - name: prepare-package-Release
        shell: cmd
        run: |
          mkdir Release\
          mkdir Release\ILSD
          copy "Binaries\ILSD\Release\*" "Release\ILSD\"
          
      # Prepare package Debug
      - name: prepare-package-Debug
        shell: cmd
        run: |
          mkdir Debug\
          mkdir Debug\ILSD
          copy "Binaries\ILSD\Debug\*" "Debug\ILSD\"
          
      # Generate artifact Debug
      - uses: actions/upload-artifact@v2
        with:
          name: ILSD Debug
          path: Debug/
    
      # Generate artifact Release
      - uses: actions/upload-artifact@v2
        with:
          name: ILSD Release
          path: Release/



  # Release
  build-nightly-windows:
    runs-on: windows-2019
    needs: [build-windows]
    
    steps:
    
    # Download artifact
    - uses: actions/download-artifact@v2
      with:
        name: ILSD Debug
        path: Debug/
      
    - uses: actions/download-artifact@v2
      with:
        name: ILSD Release
        path: Release/
      
    # Zip
    - run: |
        mkdir Release\ILSD\ressources
        mkdir Release\ILSD\ressources\captures
        mkdir Release\ILSD\ressources\tiles
        mkdir Release\ILSD\ressources\strokes
        mkdir Release\ILSD\ressources\nvm
        mkdir Release\ILSD\ressources\til
        mkdir Release\ILSD\ressources\til\sub
        mkdir Release\ILSD\ressources\til\mid
        mkdir Release\ILSD\ressources\til\sol
        
        mkdir Debug\ILSD\ressources
        mkdir Debug\ILSD\ressources\captures
        mkdir Debug\ILSD\ressources\tiles
        mkdir Debug\ILSD\ressources\strokes
        mkdir Debug\ILSD\ressources\nvm
        mkdir Debug\ILSD\ressources\til
        mkdir Debug\ILSD\ressources\til\sub
        mkdir Debug\ILSD\ressources\til\mid
        mkdir Debug\ILSD\ressources\til\sol
     
        powershell Compress-Archive -Path Release\* -DestinationPath ILSD-Release.zip
        powershell Compress-Archive -Path Debug\* -DestinationPath ILSD-Debug.zip
      shell: cmd
    
    # Release
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "ILSD"
        prerelease: true
        title: "ILSD"
        files: | 
            ILSD-Debug.zip
            ILSD-Release.zip
